version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: dashboard_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dashboard
      MYSQL_USER: university_user
      MYSQL_PASSWORD: university_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/migrations:/docker-entrypoint-initdb.d
    networks:
      - university_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dashboard_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: dashboard
      DB_USER: university_user
      DB_PASSWORD: university_password
      JWT_SECRET: your_super_secret_jwt_key_here_make_it_long_and_random
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      MAX_FILE_SIZE: 10485760
      ALLOWED_FILE_TYPES: application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,image/jpeg,image/png
      BCRYPT_ROUNDS: 12
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - university_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dashboard_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_APP_NAME: University Portal
      VITE_APP_VERSION: 1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - university_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  university_network:
    driver: bridge
